# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6544f8229f65f6657fa3b7250a6b00da6e2d7afaf20dbe3fac89bf91acd0553ae1c3c8527947a651cf5f89c0e2edc472886c2c4ccd148d844d826a90b2d8e6e

test:
  secret_key_base: f05c8bbf8a93fdc1e068b955ba1ab255641e8b185466c3459a9cc6f1dd5ab85db3fab08f8607204bc06f5b340bb34467081f609a15325d450495c0b0f2d8aaa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
